---
title: "Quantifying Mollusc Kit Digestion Gels"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tidy Data

Jan 14 2021

```{r lib, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
```

```{r import}
dat <- read.table("/Users/hannah/gitHub/Spisula/Work/Quantification/Ss_MollsucKitDigest_1_12_20_r2_a.txt",header=F)
#make the second row the header after removing the first row
names(dat) <- as.matrix(dat[2, ])
dat <- dat[-2, ]
dat[] <- lapply(dat, function(x) type.convert(as.character(x)))
#rename column headers
colnames(dat)[which(names(dat) == "Offset(%)")] <- "Offset_percent"
colnames(dat)[which(names(dat) == "Offset(pix)")] <- "Offset_pix"
#remove the lines with names, replace with a collumn that has the lane name
dat <- dplyr::filter(dat, Background != "----------")
#remove other headers
dat <- dplyr::filter(dat, Background != "Background")
#add lane name
Lanes <- c(rep("MW_uncut",271),rep("MW_5",271),rep("MW_35",271),rep("MW_uncut2",271),rep("MW_1",271),rep("MW_05",271))
dat <- cbind(dat, Lanes)


head(dat)

#does not work:
transform(dat, Offset_percent = as.numeric(Offset_percent), 
          Offset_pix = as.numeric(Offset_pix),
          Profile = as.numeric(Profile),
          Background  = as.numeric(Background ))

#works:
dat$Offset_percent <- as.numeric(as.character(dat$Offset_percent))
dat$Profile <- as.numeric(as.character(dat$Profile))
dat$Background <- as.numeric(as.character(dat$Background))

ggplot(dat, aes(x = Offset_percent, y = Profile, color = Lanes)) + geom_line()


ggplot(dat, aes(x = Offset_percent)) + geom_line(aes(y = Profile)) + geom_line(aes(y = Background, color="Background (aka smear)")) + facet_wrap(~Lanes)

  
  
dat$Offset_percent <- as.numeric(as.character(dat$Offset_percent))
dat$Profile <- as.numeric(as.character(dat$Profile))
as.numeric(as.character(dat$Offset_percent))
as.numeric(as.character(dat$Offset_percent))

mw18 <- dat
quan_mw_18 <- mw18


quan_mw_18$Offset_percent <- as.numeric(as.character(quan_mw_18$Offset_percent))
quan_mw_18$Profile <- as.numeric(as.character(quan_mw_18$Profile))
quan_mw_18$Background <- as.numeric(as.character(quan_mw_18$Background))
ggplot(quan_mw_18, aes(x = Offset_percent)) + geom_line(aes(y = Profile)) + facet_wrap(~Lanes) + geom_line(aes(y = Background, color="Background"))
ggplot(quan_mw_18, aes(x = Offset_percent, y = Profile, color = Lanes)) + geom_line()

# Wells stop at 13%
# Max Profile from 13 to 25
# Max Background from 20 to 75
# Average Background from 30 to 60 (with variance)


#create a for loop to do this across all of them,
#plot x=offset_percent, y= profile, and y2= background, grouped in plots by lanes 

#find a peak between 12 and 25, ratio with the peak between 30 and 75 or maybe an average of 30-75
#
# MW_018
# MW_027
# my MW_027
# CTM_006
# PB_001
# sol_chloro
# PB_005
# WF_003

```


``` {r more}
dat <- read.table("/Users/hannah/gitHub/Spisula/Work/Quantification/Ss_MollsucKitDigest_1_12_20_r2_b.txt",header=F)
#make the second row the header after removing the first row
names(dat) <- as.matrix(dat[2, ])
dat <- dat[-2, ]
dat[] <- lapply(dat, function(x) type.convert(as.character(x)))
#rename column headers
colnames(dat)[which(names(dat) == "Offset(%)")] <- "Offset_percent"
colnames(dat)[which(names(dat) == "Offset(pix)")] <- "Offset_pix"
#remove the lines with names, replace with a collumn that has the lane name
dat <- dplyr::filter(dat, Background != "----------")
#remove other headers
dat <- dplyr::filter(dat, Background != "Background")
#add lane name
Lanes <- c(rep("MW27_uncut",271),rep("MW27_5",271),rep("MW27_35",271),rep("MW27_uncut2",271),rep("MW27_1",271),rep("MW27_05",271))
dat <- cbind(dat, Lanes)
dat$Offset_percent <- as.numeric(as.character(dat$Offset_percent))
dat$Profile <- as.numeric(as.character(dat$Profile))
dat$Background <- as.numeric(as.character(dat$Background))

quan_mw_27 <- dat


#rep
dat <- read.table("/Users/hannah/gitHub/Spisula/Work/Quantification/Ss_MollsucKitDigest_1_12_20_r2_c.txt",header=F)
#make the second row the header after removing the first row
names(dat) <- as.matrix(dat[2, ])
dat <- dat[-2, ]
dat[] <- lapply(dat, function(x) type.convert(as.character(x)))
#rename column headers
colnames(dat)[which(names(dat) == "Offset(%)")] <- "Offset_percent"
colnames(dat)[which(names(dat) == "Offset(pix)")] <- "Offset_pix"
#remove the lines with names, replace with a collumn that has the lane name
dat <- dplyr::filter(dat, Background != "----------")
#remove other headers
dat <- dplyr::filter(dat, Background != "Background")
#add lane name
Lanes <- c(rep("MW27rep_uncut",271),rep("MW27rep_5",271),rep("MW27rep_35",271),rep("MW27rep_uncut2",271),rep("MW27rep_1",271),rep("MW27rep_05",271))
dat <- cbind(dat, Lanes)
dat$Offset_percent <- as.numeric(as.character(dat$Offset_percent))
dat$Profile <- as.numeric(as.character(dat$Profile))
dat$Background <- as.numeric(as.character(dat$Background))

quan_mw_27_rep <- dat

# CTM_006
dat <- read.table("/Users/hannah/gitHub/Spisula/Work/Quantification/Ss_MollsucKitDigest_1_12_20_r2_d.txt",header=F)
#make the second row the header after removing the first row
names(dat) <- as.matrix(dat[2, ])
dat <- dat[-2, ]
dat[] <- lapply(dat, function(x) type.convert(as.character(x)))
#rename column headers
colnames(dat)[which(names(dat) == "Offset(%)")] <- "Offset_percent"
colnames(dat)[which(names(dat) == "Offset(pix)")] <- "Offset_pix"
#remove the lines with names, replace with a collumn that has the lane name
dat <- dplyr::filter(dat, Background != "----------")
#remove other headers
dat <- dplyr::filter(dat, Background != "Background")
#add lane name
Lanes <- c(rep("ctm6_uncut",271),rep("ctm6_5",271),rep("ctm6_35",271),rep("ctm6_uncut2",271),rep("ctm6_1",271),rep("ctm6_05",271))
dat <- cbind(dat, Lanes)
dat$Offset_percent <- as.numeric(as.character(dat$Offset_percent))
dat$Profile <- as.numeric(as.character(dat$Profile))
dat$Background <- as.numeric(as.character(dat$Background))
quan_ctm_6<-dat



# PB_001
dat <- read.table("/Users/hannah/gitHub/Spisula/Work/Quantification/Ss_MollsucKitDigest_1_12_20_r2_e.txt",header=F)
names(dat) <- as.matrix(dat[2, ])
dat <- dat[-2, ]
dat[] <- lapply(dat, function(x) type.convert(as.character(x)))
colnames(dat)[which(names(dat) == "Offset(%)")] <- "Offset_percent"
colnames(dat)[which(names(dat) == "Offset(pix)")] <- "Offset_pix"
dat <- dplyr::filter(dat, Background != "----------")
dat <- dplyr::filter(dat, Background != "Background")
Lanes <- c(rep("pb1_uncut",270),rep("pb1_5",270),rep("pb1_35",270),rep("pb1_uncut2",270),rep("pb1_1",270),rep("pb1_05",270))
dat <- cbind(dat, Lanes)
dat$Offset_percent <- as.numeric(as.character(dat$Offset_percent))
dat$Profile <- as.numeric(as.character(dat$Profile))
dat$Background <- as.numeric(as.character(dat$Background))
quan_pb_1<-dat


# sol_chloro
dat <- read.table("/Users/hannah/gitHub/Spisula/Work/Quantification/Ss_MollsucKitDigest_1_12_20_r2_f.txt",header=F)
names(dat) <- as.matrix(dat[2, ])
dat <- dat[-2, ]
dat[] <- lapply(dat, function(x) type.convert(as.character(x)))
colnames(dat)[which(names(dat) == "Offset(%)")] <- "Offset_percent"
colnames(dat)[which(names(dat) == "Offset(pix)")] <- "Offset_pix"
dat <- dplyr::filter(dat, Background != "----------")
dat <- dplyr::filter(dat, Background != "Background")
Lanes <- c(rep("chloro_uncut",267),rep("chloro_5",267),rep("chloro_35",267),rep("chloro_uncut2",267),rep("chloro_1",267),rep("chloro_05",267))
dat <- cbind(dat, Lanes)
dat$Offset_percent <- as.numeric(as.character(dat$Offset_percent))
dat$Profile <- as.numeric(as.character(dat$Profile))
dat$Background <- as.numeric(as.character(dat$Background))
quan_chloro<-dat

# PB_005
dat <- read.table("/Users/hannah/gitHub/Spisula/Work/Quantification/Ss_MollsucKitDigest_1_12_20_r2_g.txt",header=F)
names(dat) <- as.matrix(dat[2, ])
dat <- dat[-2, ]
dat[] <- lapply(dat, function(x) type.convert(as.character(x)))
colnames(dat)[which(names(dat) == "Offset(%)")] <- "Offset_percent"
colnames(dat)[which(names(dat) == "Offset(pix)")] <- "Offset_pix"
dat <- dplyr::filter(dat, Background != "----------")
dat <- dplyr::filter(dat, Background != "Background")
Lanes <- c(rep("pb5_uncut",267),rep("pb5_5",267),rep("pb5_35",267),rep("pb5_uncut2",267),rep("pb5_1",267),rep("pb5_05",267))
dat <- cbind(dat, Lanes)
dat$Offset_percent <- as.numeric(as.character(dat$Offset_percent))
dat$Profile <- as.numeric(as.character(dat$Profile))
dat$Background <- as.numeric(as.character(dat$Background))
quan_pb_5<-dat


# WF_003
dat <- read.table("/Users/hannah/gitHub/Spisula/Work/Quantification/Ss_MollsucKitDigest_1_12_20_r2_h.txt",header=F)
names(dat) <- as.matrix(dat[2, ])
dat <- dat[-2, ]
dat[] <- lapply(dat, function(x) type.convert(as.character(x)))
colnames(dat)[which(names(dat) == "Offset(%)")] <- "Offset_percent"
colnames(dat)[which(names(dat) == "Offset(pix)")] <- "Offset_pix"
dat <- dplyr::filter(dat, Background != 	"----------")
dat <- dplyr::filter(dat, Background != "Background")
Lanes <- c(rep("wf3_uncut",265),rep("wf3_5",265),rep("wf3_35",265),rep("wf3_uncut2",265),rep("wf3_1",265),rep("wf3_05",265))
dat <- cbind(dat, Lanes)
dat$Offset_percent <- as.numeric(as.character(dat$Offset_percent))
dat$Profile <- as.numeric(as.character(dat$Profile))
dat$Background <- as.numeric(as.character(dat$Background))
quan_wf_3<-dat
quan_wf_3 <- dplyr::filter(quan_wf_3, !is.na(Background))

```


``` {r analysis}
library(tidyverse)

quan_chloro <- dplyr::filter(quan_chloro, !is.na(Background))
quan_mw_27 <- dplyr::filter(quan_mw_27, !is.na(Background))


quan_chloro %>%
  group_by(Lanes) %>%
  summarise(mean = mean(Background[]), n = n())
quan_mw_27 %>%
  group_by(Lanes) %>%
  group_by()
  summarise(mean = mean(Background), n = n())


quan_mw_27$Background[which(quan_mw_27$Offset_percent > 60 && quan_mw_27$Lanes == "MW27_5")]

#max profile

```

``` {r ratios}
# Wells stop at 13%
# Max Profile from 13 to 30
# Max Background from 20 to 75
# Average Background from 30 to 60 (with variance)
# Some have less background calculation - instead just use profile but still max from bg to not interfere with the run off from the peak.

ggplot(quan_mw_27_rep, aes(x = Offset_percent)) + geom_line(aes(y = Profile)) + facet_wrap(~Lanes) + geom_line(aes(y = Background, color="Background"))
ggplot(quan_chloro, aes(x = Offset_percent, y = Profile, color = Lanes)) + geom_line()


# Band Peak
bp <- quan_mw_27_rep %>%
  filter(Offset_percent > 13) %>%
  filter(Offset_percent < 30) %>%
  group_by(Lanes) %>%
  summarise(peak=max(Profile))
# Smear Peak
ps <- quan_mw_27_rep %>%
  filter(Offset_percent > 25) %>%
  filter(Offset_percent < 75) %>%
  group_by(Lanes) %>%
  summarise(smear_peak=max(Background))
# Average Smear
av <- quan_mw_27_rep %>%
  filter(Offset_percent > 30) %>%
  filter(Offset_percent < 60) %>%
  group_by(Lanes) %>%
  summarise(smear_mean=mean(Profile), deviation=sd(Profile))

summ_mw_27_rep <- merge(merge(bp,ps,by="Lanes"),av,by="Lanes")

#repeat
bp <- quan_wf_3 %>%
  filter(Offset_percent > 13) %>%
  filter(Offset_percent < 30) %>%
  group_by(Lanes) %>%
  summarise(peak=max(Profile))
# Smear Peak
ps <- quan_wf_3 %>%
  filter(Offset_percent > 25) %>%
  filter(Offset_percent < 75) %>%
  group_by(Lanes) %>%
  summarise(smear_peak=max(Background))
# Average Smear
av <- quan_wf_3 %>%
  filter(Offset_percent > 30) %>%
  filter(Offset_percent < 60) %>%
  group_by(Lanes) %>%
  summarise(smear_mean=mean(Profile), deviation=sd(Profile))

summ_wf_3 <- merge(merge(bp,ps,by="Lanes"),av,by="Lanes")

#combine summaries
quan_all <- bind_rows(summ_chloro,summ_ctm_6,summ_mw_18,summ_mw_27,summ_mw_27_rep,summ_pb_1,summ_pb_5,summ_wf_3)
write.csv(quan_all, "/Users/hannah/gitHub/Spisula/Work/quantify_digests.csv", row.names = FALSE)
```
